title: CTF Writeups
destination: ../ctf        # Output goes into your main siteâ€™s /ctf folder
baseurl: /ctf              # So links work correctly
permalink: /ctf/:title/
markdown: kramdown
destination: ../ctf
baseurl: /ctf